version: "3.9"  # optional since v1.27.0
services:
  mongo:
    image: mongo
    # command: mongoimport --host mongo --db vegetable --collection potatoes --file ./data/potato-data.json --jsonArray
      # - mongoimport --host mongo --db vegetable --collection sacks --file /data/sack-data.json --jsonArray
    ports: 
      - 27017:27017
    networks:
      - potato-local

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    networks:
      - potato-local

  put-potato-in-sack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
    networks:
      - potato-local
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  potato-local:
