version: "3.9"  # optional since v1.27.0
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - potato-local

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    networks:
      - potato-local

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: sh -c "cd ./api && npm run start:dev"
    ports:
      - "9002:9002"
    networks:
      - potato-local
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  fe:
    build:
      context: .
      dockerfile: fe/Dockerfile
    command: sh -c "cd ./fe && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - potato-local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  potato-local:
