FROM mongo

COPY potato-data.json /potato-data.json
COPY sack-data.json /sack-data.json
CMD mongoimport --host mongo --db vegetable --collection potatoes --file /potato-data.json --jsonArray \
    && mongoimport --host mongo --db vegetable --collection sacks --file /sack-data.json --jsonArray
